import test from 'node:test';
import assert from 'node:assert/strict';
import {passwordHash,checkPassword,sessionToken,sessionUser,sameOrigin} from '../lib/auth.mjs';
import {parseArticle,articleMarkdown,renderMarkdown,validateArticle} from '../lib/content.mjs';

test('Şifre özeti doğru şifreyi kabul eder ve yanlışını reddeder',()=>{const hash=passwordHash('uzun-deneme-sifresi');assert(checkPassword('uzun-deneme-sifresi',hash));assert(!checkPassword('yanlis',hash));assert(!checkPassword('test','broken'));assert(!hash.includes('uzun-deneme'));});
test('Oturum değiştirilmiş imzayı ve zaman aşımını reddeder',()=>{const secret='a'.repeat(48),now=Date.now(),token=sessionToken('editor',secret,now);assert.equal(sessionUser(token,secret,now),'editor');assert.equal(sessionUser(token+'a',secret,now),null);assert.equal(sessionUser(token,secret,now+8*3600000+1),null);assert.equal(sessionUser(token,'b'.repeat(48),now),null);});
test('Yabancı siteden gelen yazma isteği kabul edilmez',()=>{assert(!sameOrigin(new Request('https://s-haber.com.tr/api/news',{headers:{origin:'https://evil.example','content-type':'application/json'}})));assert(sameOrigin(new Request('https://s-haber.com.tr/api/news',{headers:{origin:'https://s-haber.com.tr','content-type':'application/json'}})));});
test('Türkçe ve çok satırlı YAML içeriği kayıpsız korunur',()=>{const a={id:'ornek',title:'İstanbul: “Yeni haber”',category:'Gündem',date:'2026-01-01T00:00:00.000Z',author:'İdris',image:'',imageAlt:'',summary:'Birinci satır\nİkinci satır',draft:true,body:'## Başlık\n\nMetin\n\n---\n\nDevam'};assert.deepEqual(parseArticle(articleMarkdown(a),'ornek.md'),a);});
test('İçerik içindeki betikler ve zararlı bağlantılar çalıştırılabilir HTML üretmez',()=>{const html=renderMarkdown('<script>alert(1)</script>\n<img src=x onerror=alert(1)>\n<a href="javascript:alert(1)">tıkla</a>\n\n**Kalın**');assert(!html.includes('<script'));assert(!html.includes('onerror'));assert(!html.includes('javascript:'));assert(html.includes('<strong>Kalın</strong>'));});
test('Geçersiz haber adresi ve ileri tarihli yayın reddedilir',()=>{const a={id:'haber',title:'Başlık',body:'Metin',category:'Spor',date:'2026-01-01',draft:false,image:'',imageAlt:'',summary:'',author:''};assert.equal(validateArticle(a).author,'S-Haber');assert.throws(()=>validateArticle({...a,id:'../secret'}));assert.throws(()=>validateArticle({...a,date:'2099-01-01'}));assert.throws(()=>validateArticle({...a,image:'javascript:alert(1)'}));assert(validateArticle({...a,date:'2099-01-01',draft:true}).draft);});
