const $=id=>document.getElementById(id);let current=null,items=[],dirty=false,busy=false;
const fields=['title','slug','date','category','author','summary','image','imageAlt','body'];
async function api(path,options={}){let response;try{response=await fetch('/api/'+path,{...options,headers:{'Content-Type':'application/json',...options.headers}});}catch{throw new Error('Bağlantı kurulamadı. İnternet bağlantınızı kontrol edin.');}let data;try{data=await response.json();}catch{throw new Error(response.status===429?'Çok fazla deneme yapıldı. Bir dakika sonra tekrar deneyin.':'Yönetim hizmeti çalışmıyor. Sunucu kurulumunu kontrol edin.');}if(response.status===401&&!path.startsWith('auth')){showLogin();throw new Error('Oturum sona erdi. Yeniden giriş yapın.');}if(!response.ok)throw new Error(data.error||'İşlem tamamlanamadı.');return data;}
function status(message,id='editor-status'){$(id).textContent=message;}
function setDirty(value){dirty=value;$('dirty-state').textContent=value?'Kaydedilmemiş değişiklikler':'';}
function lock(value){busy=value;document.querySelectorAll('#workspace button,#workspace input,#workspace select,#workspace textarea,#logout').forEach(el=>el.disabled=value);}
function showLogin(){$('login-panel').hidden=false;$('workspace').hidden=true;$('logout').hidden=true;}
function showWorkspace(){$('login-panel').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;}
function confirmAction(message){return new Promise(resolve=>{const d=$('confirm-dialog');$('confirm-message').textContent=message;d.returnValue='cancel';d.addEventListener('close',()=>resolve(d.returnValue==='confirm'),{once:true});d.showModal();});}
const localDate=value=>{const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
function reset(){current=null;$('editor-form').reset();$('date').value=localDate(new Date());$('slug').readOnly=false;$('delete-button').hidden=true;$('preview-panel').hidden=true;$('editor-title').textContent='Yeni haber';status('');setDirty(false);renderList();}
async function list(){items=await api('news');renderList();}
function renderList(){const box=$('article-list');box.replaceChildren();const query=$('list-search').value.toLocaleLowerCase('tr-TR');for(const item of items.filter(x=>x.title.toLocaleLowerCase('tr-TR').includes(query))){const b=document.createElement('button');b.type='button';b.className='article-item';b.setAttribute('aria-current',String(current?.id===item.id));const title=document.createElement('strong');title.textContent=item.title;const meta=document.createElement('span');meta.textContent=`${item.draft?'Taslak':'Yayında'} · ${item.category}`;b.append(title,meta);b.addEventListener('click',()=>openArticle(item.id));box.append(b);}if(!box.children.length){const p=document.createElement('p');p.className='muted small';p.textContent=items.length?'Eşleşen haber yok.':'Henüz haber yok. Yeni haber ekleyebilirsiniz.';box.append(p);}}
async function openArticle(id){if(busy)return;if(dirty&&!await confirmAction('Kaydedilmemiş değişiklikler kaybolacak. Başka bir haber açılsın mı?'))return;lock(true);try{const a=await api('news?id='+encodeURIComponent(id));current=a;for(const f of fields)$(f).value=f==='slug'?a.id:f==='date'?localDate(a.date):a[f]||'';$('slug').readOnly=true;$('delete-button').hidden=false;$('editor-title').textContent=a.draft?'Taslağı düzenle':'Haberi düzenle';$('preview-panel').hidden=true;status('');setDirty(false);renderList();}catch(e){status(e.message);}finally{lock(false);}}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;status('Giriş yapılıyor…','login-status');try{await api('auth',{method:'POST',body:JSON.stringify({username:$('username').value,password:$('password').value})});$('password').value='';status('','login-status');showWorkspace();if(!current&&!dirty)reset();await list();}catch(err){status(err.message,$('workspace').hidden?'login-status':'editor-status');}finally{button.disabled=false;}});
$('logout').addEventListener('click',async()=>{if(dirty&&!await confirmAction('Kaydedilmemiş değişiklikler var. Çıkış yapılsın mı?'))return;try{await api('auth',{method:'POST',body:JSON.stringify({action:'logout'})});reset();items=[];showLogin();}catch(e){status(e.message);}});
$('new-article').addEventListener('click',async()=>{if(!dirty||await confirmAction('Kaydedilmemiş değişiklikler kaybolacak. Yeni haber açılsın mı?'))reset();});
$('refresh-list').addEventListener('click',async()=>{lock(true);try{await list();status('Haber listesi güncellendi.');}catch(e){status(e.message);}finally{lock(false);}});
$('list-search').addEventListener('input',renderList);
$('editor-form').addEventListener('input',()=>setDirty(true));
$('title').addEventListener('input',()=>{if(!current)$('slug').value=$('title').value.toLocaleLowerCase('tr-TR').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,100);});
$('editor-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const draft=e.submitter?.dataset.save!=='publish';if(!draft&&!await confirmAction('Bu haber kaydedilecek ve otomatik site yayını tamamlandığında herkes tarafından görülebilecek. Yayınlansın mı?'))return;const a={};for(const f of fields)a[f==='slug'?'id':f]=$(f).value;a.date=new Date(a.date).toISOString();a.draft=draft;if(current)a.sha=current.sha;lock(true);status('Kaydediliyor…');try{const result=await api('news'+(current?'?id='+encodeURIComponent(current.id):''),{method:current?'PUT':'POST',body:JSON.stringify(a)});current={...a,sha:result.sha};$('slug').readOnly=true;$('delete-button').hidden=false;$('editor-title').textContent=draft?'Taslağı düzenle':'Haberi düzenle';setDirty(false);status(result.message);try{await list();}catch{status(result.message+' Liste yenilenemedi; daha sonra yenileyebilirsiniz.');}}catch(err){status(err.message);}finally{lock(false);}});
$('delete-button').addEventListener('click',async()=>{if(!current||!await confirmAction('Haber depodan silinecek ve sonraki site yayınında kaldırılacak. Silinsin mi?'))return;lock(true);try{await api('news?id='+encodeURIComponent(current.id),{method:'DELETE',body:JSON.stringify({sha:current.sha})});reset();status('Haber silindi. Site yayını tamamlandığında kaldırılacak.');await list();}catch(e){status(e.message);}finally{lock(false);}});
$('preview-button').addEventListener('click',async()=>{lock(true);try{const result=await api('news',{method:'POST',body:JSON.stringify({action:'preview',body:$('body').value})});$('preview-content').innerHTML=result.html;$('preview-panel').hidden=false;$('preview-panel').scrollIntoView({behavior:'auto'});}catch(e){status(e.message);}finally{lock(false);}});
$('upload').addEventListener('change',async()=>{const file=$('upload').files[0];if(!file)return;if(file.size>3*1024*1024){status('Görsel en fazla 3 MB olabilir.');return;}lock(true);status('Görsel yükleniyor…');try{const content=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const result=await api('upload',{method:'POST',body:JSON.stringify({content})});$('image').value=result.url;setDirty(true);status('Görsel yüklendi. Haberi kaydetmeyi unutmayın.');}catch(e){status(e.message);}finally{lock(false);$('upload').value='';}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
(async()=>{try{const session=await api('auth');if(session.authenticated){showWorkspace();reset();await list();}}catch(e){status(e.message,$('workspace').hidden?'login-status':'editor-status');}})();
