backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "haberler"
    label: "Haberler"
    folder: "haberler"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Haber Başlığı", name: "title", widget: "string" }
      - { label: "Yayın Tarihi", name: "date", widget: "datetime" }
      - { label: "Kategori", name: "category", widget: "select", options: ["Gündem", "Ekonomi", "Spor", "Teknoloji"] }
      - { label: "Haber Görseli", name: "image", widget: "image" }
      - { label: "Haber İçeriği", name: "body", widget: "markdown" }
