import {readFile,writeFile,mkdir,readdir,cp,rm} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {parseArticle,renderMarkdown,escape as e,summary,categories} from '../lib/content.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const out=path.join(root,'dist');
if(path.dirname(out)!==root||path.basename(out)!=='dist')throw new Error('Geçersiz çıktı klasörü.');
await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});
const cfg=JSON.parse(await readFile(path.join(root,'site.json'),'utf8'));
await cp(path.join(root,'assets'),path.join(out,'assets'),{recursive:true});
const origin=new URL(cfg.url).origin;
const articles=[];for(const file of await readdir(path.join(root,'haberler'))){if(file.endsWith('.md')){const a=parseArticle(await readFile(path.join(root,'haberler',file),'utf8'),file);if(!a.draft&&Date.parse(a.date)<=Date.now()){if(!a.title||!Number.isFinite(Date.parse(a.date)))throw new Error(`${file}: başlık veya tarih geçersiz.`);articles.push(a);}}}
articles.sort((a,b)=>Date.parse(b.date)-Date.parse(a.date)||a.id.localeCompare(b.id));
const date=a=>new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Istanbul'}).format(new Date(a.date));
const href=a=>`/haber/${encodeURIComponent(a.id)}/`;
const nav=categories.map(c=>`<a href="/?cat=${encodeURIComponent(c)}" data-category="${e(c)}">${e(c)}</a>`).join('');
function layout(title,body,{url='/',description=cfg.description,noindex=false,schema=null}={}){return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} | S-Haber</title><meta name="description" content="${e(description)}"><meta name="theme-color" content="#c9202b">${noindex?'<meta name="robots" content="noindex,nofollow">':`<link rel="canonical" href="${e(origin+url)}">`}<meta property="og:type" content="${schema?'article':'website'}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${e(origin+url)}"><meta property="og:locale" content="tr_TR"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="alternate" type="application/rss+xml" title="S-Haber RSS" href="/rss.xml"><link rel="stylesheet" href="/assets/news.css"><script src="/assets/news.js" defer></script>${schema?`<script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script>`:''}</head><body><a class="skip" href="#icerik">İçeriğe geç</a><div class="topline"><div class="container"><span data-today>S-Haber</span><a href="/kunye/">Künye</a></div></div><header class="masthead"><div class="container masthead-row"><a class="logo" href="/" aria-label="S-Haber ana sayfa">S<span>-</span>HABER<span>.</span></a><form class="search-form" role="search" action="/"><label hidden for="news-search">Haber ara</label><input id="news-search" name="q" data-search type="search" placeholder="Haberlerde ara…" aria-label="Haberlerde ara"><button type="submit">Ara</button></form><button type="button" class="theme-toggle" data-theme aria-pressed="false">Koyu görünüm</button></div><nav class="main-nav" aria-label="Ana menü"><div class="container"><a href="/" data-home>Ana sayfa</a>${nav}<a class="nav-extra" href="/anket/">Anket</a><a href="/anneye-ozel.html">Özel</a></div></nav></header><main class="container content" id="icerik">${body}</main><footer class="site-footer"><div class="container"><div class="footer-row"><a class="logo" href="/">S<span>-</span>HABER<span>.</span></a><nav class="footer-links" aria-label="Alt menü"><a href="/kunye/">Künye ve iletişim</a><a href="/rss.xml">RSS</a><a href="/admin/">Yönetim paneli</a></nav></div><div class="footer-bottom">© ${new Date().getFullYear()} S-Haber · Genel Yayın Yönetmeni: ${e(cfg.editor)}</div></div></footer></body></html>`;}
async function put(p,text){const dest=path.join(out,p);await mkdir(path.dirname(dest),{recursive:true});await writeFile(dest,text);}
const card=a=>`<article class="card" data-title="${e(a.title+' '+summary(a))}" data-category="${e(a.category)}">${a.image?`<a href="${href(a)}" tabindex="-1" aria-hidden="true"><img src="${e(a.image)}" alt="${e(a.imageAlt)}" loading="lazy" width="640" height="400"></a>`:''}<div class="card-body"><span class="category">${e(a.category)}</span><h2><a href="${href(a)}">${e(a.title)}</a></h2><p>${e(summary(a))}</p><time class="metadata" datetime="${e(a.date)}">${date(a)}</time></div></article>`;
let lead='';if(articles.length){const a=articles[0];lead=`<section class="lead-grid" aria-label="Öne çıkan haberler"><article class="feature">${a.image?`<a href="${href(a)}" tabindex="-1" aria-hidden="true"><img src="${e(a.image)}" alt="${e(a.imageAlt)}" width="900" height="506" fetchpriority="high"></a>`:''}<div class="feature-copy"><span class="category">${e(a.category)}</span><h2><a href="${href(a)}">${e(a.title)}</a></h2><p>${e(summary(a))}</p><time class="metadata" datetime="${e(a.date)}">${date(a)}</time></div></article><aside class="latest"><h2>Son haberler</h2><ol>${articles.slice(0,5).map(x=>`<li><a href="${href(x)}">${e(x.title)}</a><time datetime="${e(x.date)}">${date(x)}</time></li>`).join('')}</ol></aside></section>`;}
await put('index.html',layout('Gündem, ekonomi, spor ve teknoloji',`${lead}<div class="section-heading"><h1 data-grid-title>Tüm haberler</h1><span class="muted small">S-Haber</span></div><section class="news-grid" data-news-grid aria-label="Haberler">${articles.map(card).join('')}${articles.length?'':`<div class="empty"><span class="section-label">S-Haber</span><h2>İlk haberlerimiz yakında burada.</h2><p>Gündem, ekonomi, spor ve teknoloji haberleri bu sayfada yayınlanacak.</p></div>`}</section><div class="empty" data-filter-empty hidden role="status"><h2>Aradığınız haber bulunamadı.</h2><p>Farklı bir kelime deneyebilir veya <a href="/">tüm haberlere dönebilirsiniz.</a></p></div>`));
for(const a of articles){await put(`haber/${a.id}/index.html`,layout(a.title,`<div class="article-shell"><nav class="breadcrumb" aria-label="İçerik yolu"><a href="/">Ana sayfa</a> / <a href="/?cat=${encodeURIComponent(a.category)}">${e(a.category)}</a></nav><article><span class="category">${e(a.category)}</span><h1>${e(a.title)}</h1>${a.summary?`<p class="article-intro">${e(a.summary)}</p>`:''}<div class="article-meta"><span>${e(a.author)}</span><time datetime="${e(a.date)}">${date(a)}</time></div>${a.image?`<img class="article-image" src="${e(a.image)}" alt="${e(a.imageAlt)}" width="1200" height="675">`:''}<div class="article-body">${renderMarkdown(a.body)}</div><div class="article-end"><a href="/?cat=${encodeURIComponent(a.category)}">Diğer ${e(a.category)} haberleri →</a></div></article></div>`,{url:href(a),description:summary(a),schema:{'@context':'https://schema.org','@type':'NewsArticle',headline:a.title,datePublished:a.date,author:{'@type':'Person',name:a.author},publisher:{'@type':'Organization',name:'S-Haber'},mainEntityOfPage:origin+href(a),...(a.image?{image:new URL(a.image,origin).href}:{})}}));}
const facts=[['Genel Yayın Yönetmeni',cfg.editor],['Yayıncı',cfg.publisher],['E-posta',cfg.email],['Telefon',cfg.phone],['Adres',cfg.address]].filter(([,v])=>v);
await put('kunye/index.html',layout('Künye ve iletişim',`<div class="article-shell"><span class="section-label">S-Haber</span><h1>Künye ve iletişim</h1><dl class="facts">${facts.map(([k,v])=>`<dt>${e(k)}</dt><dd>${k==='E-posta'?`<a href="mailto:${e(v)}">${e(v)}</a>`:e(v)}</dd>`).join('')}</dl></div>`,{url:'/kunye/'}));
await put('404.html',layout('Sayfa bulunamadı','<div class="empty"><span class="section-label">404</span><h1>Bu sayfa bulunamadı.</h1><p>Adres değişmiş veya haber yayından kaldırılmış olabilir.</p><p><a href="/">Ana sayfaya dön →</a></p></div>',{noindex:true}));
await put('haber-detay.html',layout('Haber',`<div class="empty"><h1 data-legacy-title>Haber aranıyor…</h1><p><a href="/">Ana sayfaya dön</a></p></div><script src="/assets/legacy.js" defer></script>`,{noindex:true}));
await put('assets/legacy.js',`const valid=${JSON.stringify(articles.map(a=>a.id))};const id=(new URLSearchParams(location.search).get('haber')||'').replace(/\\.md$/,'');if(valid.includes(id))location.replace('/haber/'+encodeURIComponent(id)+'/');else document.querySelector('[data-legacy-title]').textContent='Haber bulunamadı veya yayında değil.';`);
await put('anket/index.html',layout('Forma anketi',`<div class="section-heading"><h1>En sevdiğiniz forma hangisi?</h1></div><p class="muted">Bir forma seçip oyunuzu gönderin. Oylar anonimdir. Aynı tarayıcıyla bir kez oy kullanabilirsiniz.</p><form id="poll-form"><fieldset style="border:0;padding:0;margin:0"><legend class="small">Tercihinizi seçin</legend><div class="poll-grid">${[1,2,3,4,5,6].map(n=>`<div class="poll-card"><img src="/silincek/forma${n}.jpeg" alt="Forma ${n}" width="200" height="300" loading="lazy"><label><input type="radio" name="choice" value="${n}" required> Forma ${n}</label><output data-result="${n}">—</output></div>`).join('')}</div></fieldset><p><button class="button" type="submit">Oyumu gönder</button></p></form><p id="poll-status" class="status" role="status"></p><script src="/assets/poll.js" defer></script>`,{url:'/anket/'}));
await put('silincek/anket.html','<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=/anket/"><title>Anket | S-Haber</title></head><body><a href="/anket/">Ankete git</a></body></html>');
const urls=['/','/kunye/','/anket/',...articles.map(href)];
await put('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${e(origin+u)}</loc></url>`).join('')}</urlset>`);
await put('robots.txt',`User-agent: *\nAllow: /\nDisallow: /admin/\nDisallow: /api/\nDisallow: /anneye-ozel.html\nDisallow: /anneye-surpriz.html\nSitemap: ${origin}/sitemap.xml\n`);
await put('rss.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>S-Haber</title><link>${e(origin)}</link><description>${e(cfg.description)}</description><language>tr</language>${articles.slice(0,30).map(a=>`<item><title>${e(a.title)}</title><link>${e(origin+href(a))}</link><guid>${e(origin+href(a))}</guid><pubDate>${new Date(a.date).toUTCString()}</pubDate><description>${e(summary(a))}</description></item>`).join('')}</channel></rss>`);
await put('favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="10" fill="#c9202b"/><text x="32" y="48" font-family="Arial,sans-serif" font-weight="bold" font-size="46" text-anchor="middle" fill="white">S</text></svg>');
for(const p of ['img','admin'])await cp(path.join(root,p),path.join(out,p),{recursive:true});
for(const p of ['style.css','birthday.js','birthday-surprise.js','anneye-ozel.html','anneye-surpriz.html'])await cp(path.join(root,p),path.join(out,p));
for(let n=1;n<=6;n++)await cp(path.join(root,`silincek/forma${n}.jpeg`),path.join(out,`silincek/forma${n}.jpeg`));
console.log(`${articles.length} yayınlanmış haber; ana sayfa, detaylar, anket, künye, RSS ve site haritası hazır.`);
